name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make test

    - name: clean
      run: make clean

    - name: run
      run: make run

    - name: memcheck
      run: |
        sudo apt install valgrind
        make memcheck

    - name: clean
      run: make clean
      
    - name: perfcheck
      run: |
        sudo apt install gprof
        make perfcheck

    - uses: actions/upload-artifact@v3
      with:
        name: render-artifact
        path: |
          result.png
          result-valgrind.png
          valgrind.log
          tests.log
          gprof.log
